name: CI
on:
  pull_request:
  push:
permissions:
  contents: read
jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        rust: ["stable"]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo test --no-run
    - name: Test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: cargo test
    - name: Verify that binary works
      run: |
        cargo run -- bisect-rustc --help | grep "EXAMPLES:"
        cargo run -- --help | grep "SUBCOMMANDS:"
